// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnvrNU7bDwITFRLNv-erxcMkdt1_ebu3Q',
    appId: '1:604435189510:web:a14c5a363dce1fa080d887',
    messagingSenderId: '604435189510',
    projectId: 'vanguardmoney',
    authDomain: 'vanguardmoney.firebaseapp.com',
    storageBucket: 'vanguardmoney.firebasestorage.app',
    measurementId: 'G-MVF5XW1BT5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARlm413uAueq8wZgaurQRhjxGX_oE9vHY',
    appId: '1:604435189510:android:7ee15b3e0a774ce280d887',
    messagingSenderId: '604435189510',
    projectId: 'vanguardmoney',
    storageBucket: 'vanguardmoney.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH6GlSGyvC6-idQodkt78uRNHrg5JBU1w',
    appId: '1:604435189510:ios:fc6f23fd51bfa4fb80d887',
    messagingSenderId: '604435189510',
    projectId: 'vanguardmoney',
    storageBucket: 'vanguardmoney.firebasestorage.app',
    iosBundleId: 'com.example.vanguardmoney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH6GlSGyvC6-idQodkt78uRNHrg5JBU1w',
    appId: '1:604435189510:ios:fc6f23fd51bfa4fb80d887',
    messagingSenderId: '604435189510',
    projectId: 'vanguardmoney',
    storageBucket: 'vanguardmoney.firebasestorage.app',
    iosBundleId: 'com.example.vanguardmoney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnvrNU7bDwITFRLNv-erxcMkdt1_ebu3Q',
    appId: '1:604435189510:web:59078735ef0a6fa480d887',
    messagingSenderId: '604435189510',
    projectId: 'vanguardmoney',
    authDomain: 'vanguardmoney.firebaseapp.com',
    storageBucket: 'vanguardmoney.firebasestorage.app',
    measurementId: 'G-2DM2P3NS44',
  );
}
