version: '3.9'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: egresos_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_DIALECT=mysql
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=egresos_db
      - JWT_SECRET=mi_clave_secreta_segura
      - JWT_EXPIRES_IN=1h
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db_data:
